#!/usr/bin/env bash

root="${HOME}/ui"
cd $root

# The primary reason for this is so that stow will not create symlink
# *directories*. Apparently this solves a potential subsequent linking problem
# (with stow) as described in ff444eb, although I am not sure (anymore) if that
# is really a problem or a false flag.
#
# The disadvantage with this is that this list has to be maintained, so it is
# probably preferable to remove this somehow, *if possible*.
mkdir -pv ~/.config/fontconfig
mkdir -pv ~/.config/mpd
mkdir -pv ~/.config/mpv
mkdir -pv ~/.config/ncmpcpp
mkdir -pv ~/.config/qutebrowser
mkdir -pv ~/.config/zathura
mkdir -pv ~/.emacs.d/lisp
mkdir -pv ~/.icons
mkdir -pv ~/.nixpkgs
mkdir -pv ~/.pentadactyl/colors
mkdir -pv ~/.urxvt
mkdir -pv ~/.vim/autoload
mkdir -pv ~/.xmonad
mkdir -pv ~/.Xresources.d

./bin/set-theme gruvbox-light
./bin/set-font input-9

make
for dir in */ ; do stow "${dir}"; done

# Other directories.
mkdir -pv ~/.backup
# For rtorrent, but may be removed later.
mkdir -pv ~/dl/torrents/session
mkdir -pv ~/dl/torrents/watch
mkdir -pv ~/dl/music
mkdir -pv ~/gh/forks
mkdir -pv ~/gh/themes

cd ~/gh
git clone 'https://github.com/vyp/evil-quick-scope'
git clone 'https://github.com/vyp/ui-bin'
cd ui-bin
mkdir -pv ~/.fonts
for dir in */ ; do stow -t ~ "${dir}"; done
fc-cache -fv

cd ~/gh/themes
git clone 'https://github.com/vyp/gruvbox-emacs'
git clone 'https://github.com/vyp/redbelly'

cd $root
./misc/dl-hg-packages
git submodule update --init --recursive
ln -s ~/ui/vendor/vim/vim-plug/plug.vim ~/.vim/autoload/plug.vim
xmonad --recompile
