#!/bin/bash

DIRS="
  ~/.backup
  ~/.config/bspwm
  ~/.config/dzen2
  ~/.config/mpd
  ~/.config/mpv
  ~/.config/sxhkd
  ~/.config/zathura
  ~/.emacs.d
  ~/.pentadactyl/colors
  ~/.urxvt
  ~/.vim/autoload
  ~/.vim/plugged
"

for dir in $DIRS; do
  mkdir -pv "${dir}"
done
