#!/bin/bash

mkdir -pv ~/.backup
mkdir -pv ~/.config/bspwm
mkdir -pv ~/.config/dzen2
mkdir -pv ~/.config/mpd
mkdir -pv ~/.config/mpv
mkdir -pv ~/.config/sxhkd
mkdir -pv ~/.config/zathura
mkdir -pv ~/.emacs.d
mkdir -pv ~/.pentadactyl/colors
mkdir -pv ~/.urxvt
mkdir -pv ~/.vim/autoload
mkdir -pv ~/.vim/plugged
