#!/usr/bin/env bash

# Dependencies:
#
# - youtube-dl.
# - ffmpeg.
# - lltag.
# - mpd and mpc (optional).
# - mpv (or some other media player to test trims).
# - Some $EDITOR defined.

set -u
set -e

dl_dir="${HOME}/dl/music"
mpd_pid_f="${HOME}/.config/mpd/pid"
music_dir="${HOME}/music"
playlist_dir="${HOME}/.config/mpd/playlists"
tmp_dir_name='tmp'

name_f='name'
playlist_f='playlists'
trim_f='trim'
urlf='url'

tmp_n=1
trimp_p='true'

add-to-playlist () {
  echo "${2}.ogg" >> "${playlist_dir}/${1}.m3u"
  sort -u "${playlist_dir}/${1}.m3u" -o "${playlist_dir}/${1}.m3u"
}

bell () {
  echo -e "\a"
}

# In a separate function in case I can get TRAP working properly... (if the
# internet connection suddenly dies or something).
cleanup () {
  remove-file-if-exists "$name_f" "$playlist_f" "$trim_f" "$urlf"
  local current_dir="$(pwd)"
  cd ..
  rmdir -v "$current_dir"
}

get-title () {
  echo "$(youtube-dl --get-title ${1})"
}

remove-file-if-exists () {
  for file in "$@"; do
    [[ -f "$file" ]] && rm -v "$file"
  done
}

if [[ ! -d $dl_dir ]]; then
  read -p "Download directory '$dl_dir' does not exist, create it? (y/N)" \
       createp

  if [[ "$createp" == "y" ]]; then
    mkdir -pv $dl_dir
  else
    echo 'Aborting download.'
    exit 1
  fi
fi

while [[ -d "${dl_dir}/${tmp_dir_name}$tmp_n" ]]; do
  tmp_n=$(($tmp_n + 1))
done

mkdir -pv "${dl_dir}/${tmp_dir_name}$tmp_n"
cd "${dl_dir}/${tmp_dir_name}$tmp_n"

# List any already existing playlists to make it easier to select additions for
# the current download.
[[ ! -d $playlist_dir ]] && mkdir -pv $playlist_dir || printf \
  "\n$(ls $playlist_dir | sed -e 's:\.[^./]*$::' | tr '\n' ' ')\n" | fold -w \
  80 -s | sed 's/ *$//' > $playlist_f

if [[ $# -eq 0 ]]; then
  $EDITOR $urlf
  get-title "$(< $urlf)" > $name_f
  bell
  $EDITOR $name_f $playlist_f $trim_f
else
  echo "$1" > $urlf
  get-title "$1" > $name_f
  bell
  $EDITOR $name_f $playlist_f $trim_f
fi

name="$(< $name_f)"
# TODO: Download the generally less in size .ogg files instead?
youtube-dl -f 43 --no-part -o "${name}.webm" "$(< $urlf)"
bell

while [[ $trimp_p == 'true' ]]; do
  if [[ -s $trim_f ]]; then
    trim_times="$(< $trim_f)"

    if [[ "$trim_times" == *"-"* ]]; then
      trim_start="$(awk -F '-' '{print $1}' <<< $trim_times)"
      trim_end="$(awk -F '-' '{print $2}' <<< $trim_times)"

      if [[ -z "$trim_start" ]]; then
        # Only trim end.
        ffmpeg -y -i "${name}.webm" -to "00:$trim_end" -vn -acodec copy \
               "${name}.ogg"
      else
        # Trim both sides.
        ffmpeg -y -i "${name}.webm" -ss "00:$trim_start" -to "00:$trim_end" \
               -vn -acodec copy "${name}.ogg"
      fi
    else
      # Only trim beginning.
      ffmpeg -y -i "${name}.webm" -ss "00:$trim_times" -vn -acodec copy \
             "${name}.ogg"
    fi

    mpv --no-video --loop=inf "${name}.ogg"
    read -p "Is it good? (y/N)" trim_status
    [[ "$trim_status" == "y" ]] && trimp_p='false' || $EDITOR $trim_f
  else
    # No trimming -> automatically convert and proceed without asking for
    # confirmation.
    ffmpeg -y -i "${name}.webm" -vn -acodec copy "${name}.ogg"
    trimp_p='false'
  fi
done

lltag --format '%a - %t' --yes "${name}.ogg"
add-to-playlist all "$name"

for playlist in $(head -n 1 $playlist_f); do
  add-to-playlist $playlist "$name"
done

mv -v "${name}.ogg" "${music_dir}"
rm -v "${name}.webm"
[[ -s "$mpd_pid_f" ]] && mpc update
cleanup
bell
