#!/bin/sh

bspc config normal_border_color "#2d2d2d"
bspc config active_border_color "#f2f0ec"
bspc config focused_border_color "#747369"
bspc config presel_border_color "#a09f93"
bspc config urgent_border_color "#f2777a"
