[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

[buildPlans.iosevka-custom.variants.design]
capital-a = "curly-serifless"
capital-c = "bilateral-inward-serifed"
capital-g = "toothless-corner-inward-serifed-capped"
capital-j = "flat-hook-serifed"
capital-p = "closed-motion-serifed"
capital-q = "crossing"
capital-u = "toothless-corner"
capital-v = "curly"
capital-w = "straight"
capital-y = "curly-motion-serifed"
capital-z = "straight-serifless"
b = "toothless-corner"
d = "toothless-corner-serifless"
f = "flat-hook"
g = "single-storey-earless-corner-flat-hook"
i = "zshaped"
j = "flat-hook-serifless"
l = "zshaped"
n = "straight"
p = "earless-corner"
q = "earless-corner"
r = "serifless"
t = "flat-hook"
y = "curly"
eszet = "sulzbacher-descending"
lower-iota = "zshaped"
one = "base-long-top-serif"
four = "open-non-crossing"
six = "closed-contour"
nine = "closed-contour"
asterisk = "hex-low"
underscore = "high"
caret = "low"
paren = "large-contour"
brace = "curly-flat-boundary"
ampersand = "et-toothless-corner"
at = "short"
dollar = "through-cap"
cent = "through"
percent = "rings-continuous-slash-also-connected"
lig-ltgteq = "flat"
question = "corner-flat-hooked"

[buildPlans.iosevka-custom.variants.italic]
capital-a = "straight-top-serifed"
capital-b = "standard-interrupted-bilateral-serifed"
capital-c = "unilateral-inward-serifed"
capital-e = "serifed"
capital-f = "serifed"
capital-g = "toothless-rounded-inward-serifed-hooked"
capital-h = "top-left-bottom-right-serifed"
capital-j = "flat-hook-serifless"
capital-l = "motion-serifed"
capital-p = "open-motion-serifed"
capital-q = "crossing-curly-tailed"
capital-r = "curly-open"
capital-s = "bilateral-serifed"
capital-u = "motion-serifed"
capital-v = "curly-motion-serifed"
capital-w = "straight-vertical-sides-motion-serifed"
capital-x = "curly-motion-serifed"
capital-z = "cursive-with-crossbar"
b = "toothless-corner-motion-serifed"
c = "unilateral-inward-serifed"
d = "toothless-corner-serifed"
f = "flat-hook-tailed"
h = "straight-top-left-serifed"
y = "cursive-flat-hook"
eszet = "sulzbacher-tailed"
six = "open-contour"
seven = "bend-crossbar"
nine = "straight-bar"
ampersand = "lower-open"
dollar = "interrupted-cap"
cent = "bar-interrupted"
percent = "rings-segmented-slash"
question = "smooth"

[buildPlans.iosevka-custom.ligations]
inherits = "haskell"

[buildPlans.iosevka-custom.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-custom.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-custom.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-custom.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
