#!/bin/bash

cd ~/ui
./misc/make-config-directories
# For automatic setup with a default theme, but this can be manually changed
# later without affecting the state of the git repository.
./bin/set-theme gruvbox-light
make

for dir in */ ; do
  stow "${dir}"
done

# TODO: Also mkdir ~/gh and clone some appropriate repos. These don't have to be
# submodules because they are developed by me. This ties into giving directory
# structure information.

# TODO: Run `dl-hg-packages` script somewhere here.

git submodule init
git submodule update
ln -s ~/ui/vendor/vim/vim-plug/plug.vim ~/.vim/autoload/plug.vim
