#!/bin/env bash

cd ~/etsi

IGNORE=(
  "antigen/"
  "bin/"
  "dmenu/"
  "docs/"
  "dzen2/"
  "emacs-packages/"
  "firefox/"
  "pacman/"
  "schemes/"
  "vim-plug/"
  "zathura/"
)

MAKEDIRS=true

DIRS="
  ~/.cache/mutt
  ~/.config/bspwm
  ~/.config/dzen2
  ~/.config/mpd
  ~/.config/mpv
  ~/.config/mutt
  ~/.config/sxhkd
  ~/.config/zathura
  ~/.emacs.d
  ~/.pentadactyl/colors
  ~/.urxvt
  ~/.vim/autoload
  ~/.vim/plugged
"

containsElement () {
  local e

  for e in "${@:2}"; do
    [[ "$e" == "$1" ]] &&
      return 0
  done

  return 1
}

if [ "$MAKEDIRS" = true ]; then
  for dir in $DIRS; do
    mkdir -pv "${dir}"
  done
fi

for dir in */ ; do
  containsElement "${dir}" "${IGNORE[@]}"

  if [[ $? -eq 1 ]]; then
    stow "${dir}"
  fi
done

git submodule init
git submodule update --depth 10
# emacs --batch -Q -f batch-byte-compile file.el

ln -s ~/etsi/vim-plug/plug.vim ~/.vim/autoload/plug.vim

sudo rm -vi /etc/pacman.conf
sudo stow -t / pacman
sudo stow -t / zathura

./bin/chue
