#!/bin/bash

bspc config normal_border_color "#222222"
bspc config active_border_color "#aa759f"
bspc config focused_border_color "#292929"
bspc config presel_border_color "#444444"
bspc config urgent_border_color "#ac4142"
