#!/usr/bin/env bash

. ~/ui/lemonbar/variables

while read -r line; do
  case $line in
    B*)
      ac_status="$(cut -d' ' -f3 <<< $line)"
      battery_lvl="$(cut -d' ' -f4 <<< $line | rev | cut -c 3- | rev)"

      if   [[ $battery_lvl -lt 10 ]]; then battery_clr="$battery_exlow"
      elif [[ $battery_lvl -lt 25 ]]; then battery_clr="$battery_vlow"
      elif [[ $battery_lvl -lt 50 ]]; then battery_clr="$battery_low"
      elif [[ $battery_lvl -lt 75 ]]; then battery_clr="$battery_good"
      elif [[ $battery_lvl -lt 95 ]]; then battery_clr="$battery_high"
                                      else battery_clr="$battery_full"
      fi

      if   [[ $battery_lvl -lt 20 ]]; then battery_ico=""
      elif [[ $battery_lvl -lt 30 ]]; then battery_ico=""
      elif [[ $battery_lvl -lt 40 ]]; then battery_ico=""
      elif [[ $battery_lvl -lt 50 ]]; then battery_ico=""
      elif [[ $battery_lvl -lt 60 ]]; then battery_ico=""
      elif [[ $battery_lvl -lt 70 ]]; then battery_ico=""
      elif [[ $battery_lvl -lt 80 ]]; then battery_ico=""
      elif [[ $battery_lvl -lt 90 ]]; then battery_ico=""
                                      else battery_ico=""
      fi

      if [[ $battery_lvl -lt 10 ]]; then
        ac="%{F$main_bg}%{B$battery_clr}"
      else
        ac="%{F$battery_clr}%{B-}"
      fi

      if [[ "$ac_status" == "C"* ]]; then
        ac="%{F$ac_clr}"

        if [[ $battery_lvl -lt 95 ]]; then
          ac="${ac}%{F$battery_clr}"
        else
          ac="${ac}%{F$main_bg}%{B$battery_clr}"
        fi
      fi

      battery_info="$(cut -d' ' -f4-5 <<< $line | sed 's/,//g')"
      battery="%{T2}${ac}%{T} %{T2}${battery_ico}%{T} ${battery_info//%/%%} %{F-}%{B-}"
      ;;
    player)
      # Truncate the fake 'pipe'.
      printf '' > "$panel_file"
      music_icon='%{T2}%{T}'
      playing="$(mpc status | sed -n 2p | cut -d "[" -f2 | cut -d "]" -f1)"

      if [[ $playing != "playing" ]]; then
        music="%{F$not_playing_clr}$music_icon $(mpc current)%{F-}"
      else
        current=$(mpc current)
        artist=${current%' - '*}
        not_artist=${current##*' - '}
        track=$(grep -oP '.+?(?= ft\. |\(|\z)' <<< $not_artist | sed -n 1p)
        feat=$(grep -oP '( ft\. [^(]*|\z)' <<< ${not_artist%'('*})
        mod=$(grep -oP '\(.*' <<< $not_artist)
        music="%{F$music_icon_clr}$music_icon %{F$artist_clr}${artist}%{F$not_playing_clr} - %{F$track_clr}${track}%{F$feat_clr}${feat}%{F$mod_clr}${mod}%{F-}"
      fi
      ;;
    T*)
      date=${line%' '*}
      current_time=${line##*' '}
      datetime="%{T2}%{T} ${date:1} %{T2}%{T} %{F$main_bg}00:00:00 %{F-}"
      ;;
    W*)
      workspaces=${line%%','*}
      layout=${line#*','}
      ;;
  esac
  printf "%s\n" "%{l}%{B#427b58}%{F#8ec07c} %{T2}%{T} %{F-}%{B-} ${layout} ${music}%{c}${workspaces:1}%{r}$battery $datetime%{r}$current_time "
done
