#!/bin/sh

# Does not seem to work even though it is in the example config:
# bspc config border_width 2
# bspc config window_gap 0

bspc monitor -d surf dev work pdf music view news sys misc buff

for desktop in $(bspc query -D); do
  bspc config -d $desktop border_width 2;
  bspc config -d $desktop window_gap 0;
done

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config history_aware_focus true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true

. ~/.config/bspwm/colors

~/etsi/dzen2/panel &
