#!/bin/sh

# Following does not seem to work even though it is in the example config.
# bspc config border_width 2
# bspc config window_gap 0

bspc monitor -d i ii iii iv v vi vii viii ix x

for desktop in $(bspc query -D); do
  bspc config -d $desktop border_width 2;
  bspc config -d $desktop window_gap 0;
done

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config history_aware_focus true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true

bspc config normal_border_color "#2d2d2d"
bspc config active_border_color "#f2f0ec"
bspc config focused_border_color "#747369"
bspc config presel_border_color "#a09f93"
bspc config urgent_border_color "#f2777a"
