#!/bin/bash

root="${HOME}/ui"
git_hooks_dir="${root}/misc/git-hooks"
hooks="$(find $git_hooks_dir -maxdepth 1 -type f -executable -not -name $(basename $0))"
# Depth of 4 here because that is just where all the submodules are and how this
# repository is organised; Everything is under 'vendor', then the domain name
# (so which program the submodule(s) belong to, e.g. emacs, vim etc.), and
# finally the package/plugin name.
#
# Since the 'hooks' directory will be under the directory for the package/plugin
# name, it is a depth of 4. While not very flexible, this would help prevent
# false positives.
places_to_hook="$(find ${root}/.git/modules -mindepth 4 -maxdepth 4 -type d -name hooks)"

# Passing `-d` as the first argument will remove all the symlinks instead of
# creating them.
if [[ $# -gt 0 ]] && [[ "$1" == "-d" ]]; then
  for hook in $hooks; do
    for place in $places_to_hook; do
      [[ -L "${place}/$(basename $hook)" ]] \
          && rm -v "${place}/$(basename $hook)"
    done
  done
else
  for hook in $hooks; do
    for place in $places_to_hook; do
      ln -v -s "$hook" "${place}/$(basename $hook)"
    done
  done
fi
