#!/bin/bash

root="${HOME}/ui"
update_log=$root/update-log
package="$(basename $(pwd))"

center-print () {
  local max_width=80
  local padding=1
  local width=${#1}
  local fill_char_length=$(( ($max_width - ($width + 2 * $padding)) / 2 ))
  print-fill-chars $fill_char_length
  # The 'padding' is put here manually.
  printf " $1 "
  print-fill-chars $fill_char_length
  printf "\n"
}

print-fill-chars () {
  local fill_char='_'

  for ((i = 0 ; i < $1 ; i++ )); do
    printf $fill_char
  done
}

[[ -s $update_log ]] && printf "\n" >> $update_log || echo '# vim: ft=git' >> \
  $update_log
center-print "$package -- $(date +'%d/%m/%y %H:%M:%S')" >> $update_log
git diff --stat HEAD@{1} HEAD >> $update_log
printf "\n" >> $update_log
git log @{1}.. >> $update_log
printf "\n" >> $update_log
git diff HEAD@{1} HEAD >> $update_log
echo "Updated $(tput bold)${package}:$(tput sgr0)"
git log --pretty=format:"%Cgreen%h %Cblue%s %Creset(%Cred%cr%Creset)" @{1}..
git diff --stat HEAD@{1} HEAD
