#!/usr/bin/env bash

# Panel.
main_fg='#3c3836'
main_bg='#fbf1c7'
separator_clr='#ebdbb2'

## Music.
artist_clr='#cc241d'
song_clr='#458588'
mod_clr='#d65d0e'
music_icon_clr='#b16286'
not_playing_clr='#928374'

## Workspaces.
ws_bg_clr='#fbf1c7'

focused_occupied_clr='#928374'
focused_free_clr='#928374'
focused_urgent_clr='#cc241d'

occupied_clr='#928374'
free_clr='#d5c4a1'
urgent_clr='#cc241d'

## Battery.
ac_clr='#d65d0e'
battery_exlow='#cc241d'
battery_vlow='#d65d0e'
battery_low='#d79921'
battery_good='#98971a'
battery_high='#689d6a'
battery_full='#458588'
