#!/usr/bin/env bash

. ~/ui/dzen2/variables

if [ $(pgrep -cf panel) -gt 1 ] ; then
  printf "%s\n" "The panel is already running!" >&2
  exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

# Will come.
# mpc idleloop player > "$panel_fifo" &

while read line; do
  echo "W$line" > "$panel_fifo"
done < "/dev/stdin" &

while :; do
  date +'T'%a' '%e' '%b' '%H:%M:%S > "$panel_fifo"
  sleep 1s
done &

while :; do
  acpi -b > "$panel_fifo"
  sleep 120s
done &

tail -f "$panel_fifo" \
| \
~/ui/dzen2/processor \
| \
dzen2 \
  -p \
  -ta l \
  -fn "${font}" \
  -fg "$main_fg" \
  -bg "$main_bg" &

wait
