#!/bin/sh

bspc config normal_border_color "#fbf1c7"
bspc config active_border_color "#fbf1c7"
bspc config focused_border_color "#d5c4a1"
bspc config presel_border_color "#a89984"
bspc config urgent_border_color "#cc241d"
