#!/bin/sh

bspc config normal_border_color "#ffffff"
bspc config active_border_color "#008787"
bspc config focused_border_color "#005faf"
bspc config presel_border_color "#af5f00"
bspc config urgent_border_color "#af0000"
