# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, inputs, ... }:

{
  imports =
    [ "${inputs.nixpkgs}/nixos/modules/installer/scan/not-detected.nix" ];

  boot.initrd.availableKernelModules = [
    "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  networking.hostName = "station";
  networking.wireless.enable = true;
  networking.useDHCP = false;
  # networking.interfaces.enp34s0.useDHCP = true;
  networking.interfaces.wlp3s0f0u4.useDHCP = true;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7695c728-6376-4857-9af8-2df9917450bb";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/94B9-7A06";
      fsType = "vfat";
    };

  fileSystems."/media/hdd1" =
    { device = "/dev/disk/by-uuid/97c7d7ed-53ae-416c-b531-5e0e15425040";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/7cc0508e-e917-417d-a3c8-507a80390eb8"; }
    ];

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "20.09"; # Did you read the comment?
}
